name: Local CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Application
        run: |
          cd /home/myasir/hello-python-docker
          git pull origin main
          docker compose down
          docker compose up -d --build
